baseURL = "https://ameliavulpes.github.io"
languageCode = "en-gb"
title = "Amelia"
theme = "PaperMod"

enableRobotsTXT = true
enableGitInfo = true

# --- NEW TAXONOMY SETTINGS ---
# This preserves the casing (e.g., "RNNs" instead of "rnns")
preserveTaxonomyNames = true

# This ensures URLs stay clean (lowercase) while the display name stays pretty
# Example: /tags/linear-algebra/ vs "Linear Algebra"
disablePathToLower = false
# ------------------------------

[pagination]
  pagerSize = 10

[params]
  author = "Amelia"
  ShowReadingTime = true
  ShowWordCount = true
  ShowLastMod = true
  ShowPostNavLinks = true

  math = true
  mathEngine = "mathjax"

  mainSections = ["posts"]

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/amelia-vulpes-aa570643b/"

  [[params.socialIcons]]
    name = "email"
    url = "ameliavulpes@gmail.com"

 [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ameliaf5a8b8"

  [params.breadcrumbs]
    enabled = true
  [params.profileMode]
    enabled = true
    title = "Amelia"
    subtitle = "Machine Learning · Mathematics"
    imageUrl = "pfp.jpg"
    imageWidth = 200
    imageHeight = 200



[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  # [[menu.main]]
  #   identifier = "Categories"
  #   name = "Categories"
  #   url = "/categories/"
  #   weight = 3

  # [[menu.main]]
  #   identifier = "tags"
  #   name = "Tags"
  #   url = "/tags/"
  #   weight = 3



[markup]
  [markup.goldmark]
    unsafe = true

    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true

    [markup.goldmark.extensions]
      enable = true

      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'],["\\[", "\\]"]]
          inline = [['$', '$'],["\\(", "\\)"]]

